name: Post welcome comment

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Post welcome comment
        run: echo "Welcome to my repository!"
